import React from 'react'
import { useParams } from 'react-router-dom'
import { useI18n } from '../i18n/I18nContext'

export function BriefPage() {
  const { t } = useI18n()
  const { id } = useParams()

  const sections = [
    { key: 'executiveSummary', icon: '📋', content: 'This operation concerns a challenge to a Sexual Harm Prevention Order (SHPO) under the Sexual Offences Act 2003. The primary strategic objective is to demonstrate that the proposed prohibitions are disproportionate under Article 8 of the European Convention on Human Rights, as incorporated by the Human Rights Act 1998.' },
    { key: 'legalIssues', icon: '⚖️', content: '1. Proportionality of SHPO conditions under Article 8 ECHR
2. Necessity test under SOA 2003 s.103A
3. PACE compliance during initial investigation
4. Disclosure obligations under CPIA 1996' },
    { key: 'applicableLaw', icon: '📚', content: '• Sexual Offences Act 2003 (ss.103-122)
• Human Rights Act 1998 (Article 8)
• Police and Criminal Evidence Act 1984 (ss.58, 78)
• Criminal Procedure and Investigations Act 1996
• Criminal Procedure Rules 2020 (r.28.7)' },
    { key: 'arguments', icon: '🎯', content: 'Primary: The SHPO conditions are neither necessary nor proportionate. The defendant has no relevant convictions, and the proposed restrictions on internet use would prevent legitimate employment.

Alternative: Even if some restrictions are justified, the breadth of the proposed order exceeds what is necessary to achieve the statutory objective.' },
    { key: 'strategy', icon: '🗺️', content: 'Phase 1: File preliminary objection to draft SHPO conditions
Phase 2: Obtain expert evidence on digital forensics and risk assessment
Phase 3: Prepare detailed written submissions on proportionality
Phase 4: Instruct counsel for contested hearing' },
    { key: 'risks', icon: '⚠️', content: 'High Risk: If the challenge fails, the defendant faces lifelong notification requirements and restrictive conditions.
Medium Risk: Costs implications if the challenge is unsuccessful.
Low Risk: Adverse publicity if case attracts media attention.' },
  ]

  const confidenceData = [
    { agent: 'statute_hunter', score: 95, color: 'bg-emerald-500' },
    { agent: 'case_law_miner', score: 92, color: 'bg-emerald-500' },
    { agent: 'defence_architect', score: 88, color: 'bg-emerald-500' },
    { agent: 'precedent_matcher', score: 85, color: 'bg-amber-500' },
    { agent: 'jurisdiction_scout', score: 78, color: 'bg-amber-500' },
    { agent: 'procedural_checker', score: 96, color: 'bg-emerald-500' },
    { agent: 'sentencing_advisor', score: 82, color: 'bg-amber-500' },
    { agent: 'appeal_strategist', score: 90, color: 'bg-emerald-500' },
  ]

  const overallWinProbability = 78

  return (
    <div className="max-w-5xl mx-auto p-6">
      <div className="mb-8 flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-slate-100">{t('brief.title')}</h1>
          <p className="text-slate-400 mt-1">Operation ID: {id} • Generated by S.T.A.R.S. AI</p>
        </div>
        <button className="px-4 py-2 bg-slate-800 hover:bg-slate-700 border border-slate-600 text-slate-200 rounded-lg text-sm transition-colors flex items-center gap-2">
          📄 {t('brief.exportPDF')}
        </button>
      </div>

      {/* Win Probability Banner */}
      <div className="bg-gradient-to-r from-slate-800 to-slate-700 border border-slate-600 rounded-xl p-6 mb-6">
        <div className="flex items-center justify-between">
          <div>
            <p className="text-sm text-slate-400 uppercase tracking-wider">{t('brief.winProbability')}</p>
            <p className="text-4xl font-black text-amber-400">{overallWinProbability}%</p>
          </div>
          <div className="w-32 h-32 relative">
            <svg className="w-full h-full transform -rotate-90" viewBox="0 0 36 36">
              <path
                d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                fill="none"
                stroke="#334155"
                strokeWidth="3"
              />
              <path
                d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                fill="none"
                stroke="#f59e0b"
                strokeWidth="3"
                strokeDasharray={`${overallWinProbability}, 100`}
              />
            </svg>
          </div>
        </div>
      </div>

      {/* Brief Sections */}
      <div className="space-y-6">
        {sections.map((section) => (
          <div key={section.key} className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
            <h2 className="text-lg font-semibold text-slate-200 mb-3 flex items-center gap-2">
              <span>{section.icon}</span>
              {t(`brief.${section.key}`)}
            </h2>
            <div className="text-slate-300 whitespace-pre-line leading-relaxed">
              {section.content}
            </div>
          </div>
        ))}
      </div>

      {/* Confidence Heatmap */}
      <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6 mt-6">
        <h2 className="text-lg font-semibold text-slate-200 mb-4">{t('brief.confidenceHeatmap')}</h2>
        <div className="space-y-3">
          {confidenceData.map((item) => (
            <div key={item.agent} className="flex items-center gap-4">
              <span className="text-sm text-slate-400 w-40 truncate">{t(`agents.${item.agent}`)}</span>
              <div className="flex-1 bg-slate-700/50 rounded-full h-3 overflow-hidden">
                <div
                  className={`h-full rounded-full ${item.color}`}
                  style={{ width: `${item.score}%` }}
                />
              </div>
              <span className="text-sm font-medium text-slate-300 w-10 text-right">{item.score}%</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
