export const en = {
  // Common / Branding
  app: {
    name: "S.T.A.R.S.",
    fullName: "Special Tactics and Rescue Services",
    tagline: "AI Legal Research",
    description: "Multi-Agent AI Legal Research Engine",
    poweredBy: "Powered by Kimi",
    featuredBy: "Featured by Angel Investigations",
    version: "v3.0",
  },

  // Navigation
  nav: {
    dashboard: "Dashboard",
    newCase: "New Case",
    helpAndLaws: "Help & Laws",
    accessToJustice: "Access to Justice",
    admin: "Admin",
    profile: "Profile",
    settings: "Settings",
    logout: "Logout",
  },

  // Login
  login: {
    title: "S.T.A.R.S.",
    subtitle: "Special Tactics and Rescue Services",
    email: "Email Address",
    password: "Password",
    signIn: "Sign In",
    signingIn: "Deploying...",
    demoCredentials: "Demo credentials",
    securityNote: "AES-256-GCM Encryption • SOC 2 Compliant",
    welcome: "Welcome to S.T.A.R.S.!",
    error: "Access denied",
    forgotPassword: "Forgot access code?",
  },

  // Dashboard
  dashboard: {
    title: "Mission Control",
    subtitle: "Active research operations and case status",
    totalCases: "Total Operations",
    activeResearch: "Active Research",
    completed: "Completed",
    highPriority: "High Priority",
    recentCases: "Recent Operations",
    noCases: "No active operations",
    noCasesDesc: "Launch your first mission to start AI-powered legal research",
    createCase: "Launch Operation",
    progress: "Progress",
    agentsDeployed: "Agents Deployed",
  },

  // New Case
  newCase: {
    title: "New Operation",
    subtitle: "Deploy multi-agent legal research team",
    caseTitle: "Operation Title",
    caseTitlePlaceholder: "e.g., SHPO Challenge - Operation Dewey",
    caseFacts: "Mission Brief & Intelligence",
    caseFactsPlaceholder: "Enter all available intelligence: charges, procedural history, evidence, witness statements, and tactical objectives...",
    caseFactsHint: "Include offence details, charges, procedural history, and specific objectives. The more intelligence, the better our agents can operate.",
    offenceType: "Target Classification",
    jurisdiction: "Theatre of Operations",
    priority: "Priority Level",
    documents: "Intelligence Documents",
    documentsHint: "Upload charge sheets, police reports, witness statements, or any relevant intelligence. Max 10 files, 50MB each.",
    dragDrop: "Drag & drop intelligence files here, or browse",
    fileTypes: "PDF, DOCX, TXT up to 50MB",
    launchResearch: "Deploy Agents",
    launching: "Deploying Agent Team...",
    encryptionNote: "All intelligence encrypted with AES-256-GCM",
    characters: "characters",
    minChars: "Min 10 characters",
  },

  // Case Detail
  caseDetail: {
    researchComplete: "Operation Complete!",
    redirecting: "Redirecting to briefing in 3 seconds...",
    viewNow: "View Briefing",
    overallProgress: "Mission Progress",
    agentActivityLog: "Agent Activity Log",
    elapsed: "Mission Time",
    status: {
      pending: "Awaiting Deployment",
      researching: "Agents in Field",
      cross_checking: "Cross-Validating Intel",
      synthesizing: "Compiling Briefing",
      complete: "Mission Accomplished",
      error: "Mission Failed",
    },
  },

  // Brief
  brief: {
    title: "Mission Briefing",
    executiveSummary: "Executive Summary",
    legalIssues: "Critical Issues",
    applicableLaw: "Applicable Law",
    arguments: "Tactical Arguments",
    strategy: "Mission Strategy",
    risks: "Risk Assessment",
    persuasion: "Persuasion Tactics",
    confidenceHeatmap: "Confidence Heatmap",
    winProbability: "success probability",
    exportPDF: "Export Briefing",
    primaryStrategy: "Primary Strategy",
    alternativeStrategies: "Alternative Strategies",
    keyMotions: "Key Motions to File",
    evidenceToGather: "Intelligence to Gather",
    timeline: "Recommended Timeline",
    overallRisk: "Overall Risk Assessment",
    riskMatrix: "Risk Matrix",
    mitigations: "Recommended Mitigations",
    closingArgument: "Closing Argument Architecture",
    rhetoricalStrategies: "Rhetorical Strategies",
    shpoTechniques: "SHPO-Specific Persuasion Techniques",
  },

  // Agents
  agents: {
    statute_hunter: "Statute Hunter",
    case_law_miner: "Case Law Miner",
    defence_architect: "Defence Architect",
    precedent_matcher: "Precedent Matcher",
    jurisdiction_scout: "Jurisdiction Scout",
    procedural_checker: "Procedural Checker",
    sentencing_advisor: "Sentencing Advisor",
    appeal_strategist: "Appeal Strategist",
    closing_argument_architect: "Closing Argument Architect",
    funding_advisor: "Funding & Access Advisor",
    researching: "In Field...",
    complete: "Mission Complete",
    failed: "Agent Down",
    waiting: "Awaiting Orders...",
  },

  // Settings
  settings: {
    title: "Systems Configuration",
    profile: "Operator Profile",
    security: "Security Protocols",
    notifications: "Communications",
    preferences: "System Preferences",
    language: "Interface Language",
    languageDesc: "Choose your preferred language for the S.T.A.R.S. interface",
    darkMode: "Dark Mode",
    darkModeDesc: "Toggle between dark and light tactical displays",
    dataRetention: "Data Retention Period",
    dataRetentionDesc: "Mission data will be automatically purged after this period",
    defaultJurisdiction: "Default Theatre of Operations",
    defaultPriority: "Default Priority Level",
    twoFactor: "Two-Factor Authentication",
    twoFactorDesc: "Add an extra layer of security to your operator account",
    sessions: "Active Sessions",
    saveChanges: "Save Configuration",
    password: "Access Code",
    currentPassword: "Current Access Code",
    newPassword: "New Access Code",
    confirmPassword: "Confirm New Access Code",
    emailNotifications: "Email Communications",
    caseAlerts: "Mission Alerts",
    caseAlertsDesc: "Get notified when operations complete or critical findings emerge",
    weeklyDigest: "Weekly Intelligence Digest",
    weeklyDigestDesc: "Receive a weekly summary of all mission activity",
  },

  // Profile
  profile: {
    title: "Operator Profile",
    professionalInfo: "Professional Information",
    accountDetails: "Account Details",
    recentActivity: "Recent Operations",
    role: "Clearance Level",
    organisation: "Affiliation",
    location: "Base of Operations",
    phone: "Communications",
    barNumber: "Bar Number / SRA ID",
    memberSince: "Activated",
    lastLogin: "Last Access",
    accountStatus: "Status",
    editProfile: "Edit Profile",
  },

  // Funding
  funding: {
    title: "Access to Justice",
    subtitle: "Legal representation should not be a luxury. Explore every funding route available.",
    neverAssume: "Never assume you cannot afford help.",
    important: "Critical Alert",
    hiddenCostWarning: "The hidden cost of no representation often exceeds the cost of representation itself — longer proceedings, worse outcomes, lost earnings, and emotional toll. Explore every option before standing down.",
    fundingStaircase: "The Rescue Ladder: Step-by-Step",
    step1: "Apply for Legal Aid",
    step1Desc: "Do this IMMEDIATELY through a solicitor. Do not wait.",
    step2: "Free Advice & Referral",
    step2Desc: "Contact LawWorks, Citizens Advice, and your solicitor about pro bono.",
    step3: "Explore All Routes",
    step3Desc: "Unions, crowdfunding, family loans, fixed-fee packages.",
    fundingOptions: "Rescue Routes",
    pros: "Advantages",
    cons: "Risks",
    eligibility: "Eligibility",
    howToApply: "How to Deploy",
    estimatedCost: "Estimated Cost",
    timeline: "Timeline",
    contact: "Contact",
    website: "Website",
    youAreNotAlone: "You Are Not Alone",
    notAloneDesc: "Thousands of people every year access legal representation through these routes. The system is flawed, but help exists. Start with Step 1 — apply for legal aid today. Even if you think you won\'t qualify, the assessment is free and you might be surprised.",
  },

  // FAQ
  faq: {
    title: "Tactical Support & Law Guide",
    searchPlaceholder: "Search tactical questions or legal topics...",
    legislationSummaries: "Key Legislation Summaries",
    noResults: "No intel found matching your search",
  },

  // Admin
  admin: {
    title: "Command Center",
    systemOperational: "All Systems Green",
    caseStatusBreakdown: "Mission Status Breakdown",
    agentTaskStatus: "Agent Deployment Status",
    auditLog: "Activity Log",
    filterLogs: "Filter activity...",
  },

  // Common UI
  common: {
    loading: "Deploying...",
    save: "Save",
    cancel: "Abort",
    edit: "Modify",
    delete: "Purge",
    confirm: "Confirm",
    back: "Return",
    next: "Proceed",
    done: "Complete",
    error: "System Error",
    success: "Mission Accomplished",
    warning: "Caution",
    info: "Intel",
    required: "Required",
    optional: "Optional",
    close: "Close",
    open: "Open",
    view: "View",
    download: "Download",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    all: "All",
    none: "None",
    yes: "Affirmative",
    no: "Negative",
    enabled: "Active",
    disabled: "Inactive",
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    completed: "Completed",
    failed: "Failed",
    running: "In Progress",
    queued: "Queued",
    low: "Low",
    normal: "Normal",
    high: "High",
    urgent: "Urgent",
  },
};
