export const nl = {
  app: {
    name: "S.T.A.R.S.",
    fullName: "Special Tactics and Rescue Services",
    tagline: "AI Juridisch Onderzoek",
    description: "Multi-Agent AI Juridisch Onderzoeksmotor",
    poweredBy: "Aangedreven door Kimi",
    featuredBy: "Mede mogelijk gemaakt door Angel Investigations",
    version: "v3.0",
  },
  nav: {
    dashboard: "Dashboard",
    newCase: "Nieuwe Zaak",
    helpAndLaws: "Hulp & Wetten",
    accessToJustice: "Toegang tot Recht",
    admin: "Beheer",
    profile: "Profiel",
    settings: "Instellingen",
    logout: "Uitloggen",
  },
  login: {
    title: "S.T.A.R.S.",
    subtitle: "Special Tactics and Rescue Services",
    email: "E-mailadres",
    password: "Wachtwoord",
    signIn: "Inloggen",
    signingIn: "Inloggen...",
    demoCredentials: "Demo inloggegevens",
    securityNote: "AES-256-GCM Versleuteling • SOC 2 Compliant",
    welcome: "Welkom bij S.T.A.R.S.!",
    error: "Toegang geweigerd",
    forgotPassword: "Wachtwoord vergeten?",
  },
  dashboard: {
    title: "Missie Controle",
    subtitle: "Actieve onderzoeksoperaties en zaakstatus",
    totalCases: "Totaal Operaties",
    activeResearch: "Actief Onderzoek",
    completed: "Voltooid",
    highPriority: "Hoge Prioriteit",
    recentCases: "Recente Operaties",
    noCases: "Geen actieve operaties",
    noCasesDesc: "Start uw eerste missie om AI-gestuurd juridisch onderzoek te beginnen",
    createCase: "Operatie Starten",
    progress: "Voortgang",
    agentsDeployed: "Agenten Ingezet",
  },
  newCase: {
    title: "Nieuwe Operatie",
    subtitle: "Multi-agent juridisch onderzoeksteam inzetten",
    caseTitle: "Operatie Titel",
    caseTitlePlaceholder: "bijv., SHPO Challenge - Operatie Dewey",
    caseFacts: "Missiebrief & Inlichtingen",
    caseFactsPlaceholder: "Voer alle beschikbare inlichtingen in: aanklachten, procedurele geschiedenis, bewijs, getuigenverklaringen en tactische doelstellingen...",
    caseFactsHint: "Inclusief feiten over het delict, aanklachten, procedurele geschiedenis en specifieke doelstellingen. Hoe meer inlichtingen, hoe beter onze agenten kunnen opereren.",
    offenceType: "Doelwit Classificatie",
    jurisdiction: "Operatietheater",
    priority: "Prioriteitsniveau",
    documents: "Inlichtingendocumenten",
    documentsHint: "Upload aanklachten, politierapporten, getuigenverklaringen of andere relevante inlichtingen. Max 10 bestanden, 50MB per stuk.",
    dragDrop: "Sleep inlichtingenbestanden hierheen, of blader",
    fileTypes: "PDF, DOCX, TXT tot 50MB",
    launchResearch: "Agenten Inzetten",
    launching: "Agententeam Inzetten...",
    encryptionNote: "Alle inlichtingen versleuteld met AES-256-GCM",
    characters: "tekens",
    minChars: "Min 10 tekens",
  },
  caseDetail: {
    researchComplete: "Operatie Voltooid!",
    redirecting: "Doorverwijzen naar briefing in 3 seconden...",
    viewNow: "Bekijk Briefing",
    overallProgress: "Missievoortgang",
    agentActivityLog: "Agent Activiteitenlog",
    elapsed: "Missietijd",
    status: {
      pending: "Wacht op Inzet",
      researching: "Agenten in het Veld",
      cross_checking: "Intel Cross-Valideren",
      synthesizing: "Briefing Samenstellen",
      complete: "Missie Volbracht",
      error: "Missie Mislukt",
    },
  },
  brief: {
    title: "Missiebriefing",
    executiveSummary: "Executive Samenvatting",
    legalIssues: "Kritieke Issues",
    applicableLaw: "Toepasselijk Recht",
    arguments: "Tactische Argumenten",
    strategy: "Missiestrategie",
    risks: "Risicobeoordeling",
    persuasion: "Overtuigingstactieken",
    confidenceHeatmap: "Vertrouwen Heatmap",
    winProbability: "succeskans",
    exportPDF: "Briefing Exporteren",
    primaryStrategy: "Primaire Strategie",
    alternativeStrategies: "Alternatieve Strategieën",
    keyMotions: "Belangrijke Moties om In te Dienen",
    evidenceToGather: "Te Verzamelen Inlichtingen",
    timeline: "Aanbevolen Tijdlijn",
    overallRisk: "Algemene Risicobeoordeling",
    riskMatrix: "Risicomatrix",
    mitigations: "Aanbevolen Mitigerende Maatregelen",
    closingArgument: "Slotargument Architectuur",
    rhetoricalStrategies: "Retorische Strategieën",
    shpoTechniques: "SHPO-Specifieke Overtuigingstechnieken",
  },
  agents: {
    statute_hunter: "Statutenjager",
    case_law_miner: "Jurisprudentie Mijnwerker",
    defence_architect: "Verdedigingsarchitect",
    precedent_matcher: "Precedent Matcher",
    jurisdiction_scout: "Jurisdictie Verkenner",
    procedural_checker: "Procedurele Controleur",
    sentencing_advisor: "Vonnisadviseur",
    appeal_strategist: "Beroepsstrategist",
    closing_argument_architect: "Slotargument Architect",
    funding_advisor: "Financiering & Toegang Adviseur",
    researching: "In het Veld...",
    complete: "Missie Voltooid",
    failed: "Agent Uitgeschakeld",
    waiting: "Wacht op Orders...",
  },
  settings: {
    title: "Systeemconfiguratie",
    profile: "Operator Profiel",
    security: "Beveiligingsprotocollen",
    notifications: "Communicatie",
    preferences: "Systeemvoorkeuren",
    language: "Interfacetaal",
    languageDesc: "Kies uw voorkeurstaal voor de S.T.A.R.S. interface",
    darkMode: "Donkere Modus",
    darkModeDesc: "Schakel tussen donkere en lichte tactische displays",
    dataRetention: "Gegevensbewaartermijn",
    dataRetentionDesc: "Missiegegevens worden automatisch gewist na deze periode",
    defaultJurisdiction: "Standaard Operatietheater",
    defaultPriority: "Standaard Prioriteitsniveau",
    twoFactor: "Tweestapsverificatie",
    twoFactorDesc: "Voeg een extra beveiligingslaag toe aan uw operatoraccount",
    sessions: "Actieve Sessies",
    saveChanges: "Configuratie Opslaan",
    password: "Toegangscode",
    currentPassword: "Huidige Toegangscode",
    newPassword: "Nieuwe Toegangscode",
    confirmPassword: "Bevestig Nieuwe Toegangscode",
    emailNotifications: "E-mail Communicatie",
    caseAlerts: "Missie Alerts",
    caseAlertsDesc: "Ontvang meldingen wanneer operaties voltooid zijn of kritieke bevindingen naar voren komen",
    weeklyDigest: "Wekelijks Inlichtingenoverzicht",
    weeklyDigestDesc: "Ontvang een wekelijks overzicht van alle missieactiviteit",
  },
  profile: {
    title: "Operator Profiel",
    professionalInfo: "Professionele Informatie",
    accountDetails: "Accountgegevens",
    recentActivity: "Recente Operaties",
    role: "Vrijwaringsniveau",
    organisation: "Affiliatie",
    location: "Basis van Operaties",
    phone: "Communicatie",
    barNumber: "Balienummer / SRA ID",
    memberSince: "Geactiveerd",
    lastLogin: "Laatste Toegang",
    accountStatus: "Status",
    editProfile: "Profiel Bewerken",
  },
  funding: {
    title: "Toegang tot Recht",
    subtitle: "Juridische vertegenwoordiging zou geen luxe moeten zijn. Verken elke beschikbare financieringsroute.",
    neverAssume: "Ga er nooit van uit dat u zich geen hulp kunt veroorloven.",
    important: "Kritieke Waarschuwing",
    hiddenCostWarning: "De verborgen kosten van geen vertegenwoordiging overstijgen vaak de kosten van vertegenwoordiging zelf — langere procedures, slechtere uitkomsten, inkomstenverlies en emotionele tol. Verken elke optie voordat u zich terugtrekt.",
    fundingStaircase: "De Reddingsladder: Stap-voor-Stap",
    step1: "Rechtsbijstand Aanvragen",
    step1Desc: "Doe dit ONMIDDELLIJK via een advocaat. Wacht niet.",
    step2: "Gratis Advies & Doorverwijzing",
    step2Desc: "Neem contact op met LawWorks, het Juridisch Loket en uw advocaat over pro deo.",
    step3: "Verken Alle Routes",
    step3Desc: "Vakbonden, crowdfunding, familieleningen, vaste-tariefpakketten.",
    fundingOptions: "Reddingsroutes",
    pros: "Voordelen",
    cons: "Risico's",
    eligibility: "Geschiktheid",
    howToApply: "Hoe In te Zetten",
    estimatedCost: "Geschatte Kosten",
    timeline: "Tijdlijn",
    contact: "Contact",
    website: "Website",
    youAreNotAlone: "U Bent Niet Alleen",
    notAloneDesc: "Duizenden mensen krijgen elk jaar toegang tot juridische vertegenwoordiging via deze routes. Het systeem is gebrekkig, maar hulp bestaat. Begin met Stap 1 — vandaag nog rechtsbijstand aanvragen. Zelfs als u denkt dat u niet in aanmerking komt, de beoordeling is gratis en u zou verrast kunnen zijn.",
  },
  faq: {
    title: "Tactische Ondersteuning & Wetgids",
    searchPlaceholder: "Zoek tactische vragen of juridische onderwerpen...",
    legislationSummaries: "Belangrijkste Wetssamenvattingen",
    noResults: "Geen inlichtingen gevonden die overeenkomen met uw zoekopdracht",
  },
  admin: {
    title: "Commandocentrum",
    systemOperational: "Alle Systemen Groen",
    caseStatusBreakdown: "Missiestatus Overzicht",
    agentTaskStatus: "Agent Inzetstatus",
    auditLog: "Activiteitenlog",
    filterLogs: "Filter activiteiten...",
  },
  common: {
    loading: "Inzetten...",
    save: "Opslaan",
    cancel: "Afbreken",
    edit: "Wijzigen",
    delete: "Verwijderen",
    confirm: "Bevestigen",
    back: "Terug",
    next: "Doorgaan",
    done: "Voltooien",
    error: "Systeemfout",
    success: "Missie Volbracht",
    warning: "Waarschuwing",
    info: "Inlichting",
    required: "Verplicht",
    optional: "Optioneel",
    close: "Sluiten",
    open: "Openen",
    view: "Bekijken",
    download: "Downloaden",
    search: "Zoeken",
    filter: "Filteren",
    sort: "Sorteren",
    all: "Alle",
    none: "Geen",
    yes: "Bevestigend",
    no: "Ontkennend",
    enabled: "Actief",
    disabled: "Inactief",
    active: "Actief",
    inactive: "Inactief",
    pending: "In Afwachting",
    completed: "Voltooid",
    failed: "Mislukt",
    running: "Bezig",
    queued: "In Wachtrij",
    low: "Laag",
    normal: "Normaal",
    high: "Hoog",
    urgent: "Urgent",
  },
};
